import type { Metadata } from "next";
import { Commissioner } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";

const commissioner = Commissioner({
  variable: "--font-commissioner",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={commissioner.variable}>
      <body
        suppressHydrationWarning={true}
        className={`${commissioner.variable} bg-[#FAFAFA] bg-[url('/image-hero-mobile.jpg')] lg:bg-[url('/image-hero-desktop.jpg')] bg-cover bg-no-repeat bg-center max-w-[1440px] mx-auto  antialiased`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
